### ISSUE TITLE
ValueError: byte must be in range(0, 256)

### ISSUE THREAD

**Issue by Arubinu** [fbeaudet/ips.py#3]
Hello, I have an error that I can not adjust myself because I do not know the principle of the script.

In fact there is an overshoot of the maximum value of the byte (greater than 256).
I tried with two different roms without success.

Here is the error (thanks in advance):

Traceback (most recent call last):
  File "ips.py", line 371, in <module>
    main()
  File "ips.py", line 360, in main
    taskResult = createPatch(sys.argv[2], sys.argv[3], sys.argv[4])
  File "ips.py", line 232, in createPatch
    size[x] = len(record) >> (8 - x * 8)
ValueError: byte must be in range(0, 256)

**Comment by fbeaudet** [comment]
Hi ! So https://github.com/fbeaudet/ips.py/issues/1 is still valid. =/

Thanks for the issue, I'm gonna dive back in that code.
